# Generated by Django 4.2.15 on 2024-08-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="final_video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="project",
            name="transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
