# Generated by Django 4.2.15 on 2024-08-31 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0002_project_final_video_project_transcription_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scene",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="scene",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="scene",
            name="mood",
            field=models.CharField(
                choices=[
                    ("adventure", "Adventure"),
                    ("dramatic", "Dramatic"),
                    ("happy", "Happy"),
                    ("romantic", "Romantic"),
                    ("suspense", "Suspense"),
                ],
                default="happy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="youtubedetails",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="youtubedetails",
            name="thumbnail_image",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AddField(
            model_name="youtubedetails",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="transcription",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="youtube_id",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="youtube_url",
            field=models.URLField(help_text="Enter the full YouTube URL"),
        ),
        migrations.AlterField(
            model_name="scene",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="youtubedetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="youtubedetails",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="scene",
            unique_together={("project", "order")},
        ),
    ]
