# Generated by Django 4.2.15 on 2024-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0004_scene_audio_alter_scene_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.CharField(default="finance", max_length=50),
        ),
    ]
