# Generated by Django 4.2.15 on 2024-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0005_project_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubedetails",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
