# Generated by Django 4.2.15 on 2024-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0006_youtubedetails_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
