# Generated by Django 4.2.15 on 2025-02-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0007_project_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="video_format",
            field=models.CharField(
                choices=[("landscape", "Landscape (16:9)"), ("reel", "Reel (9:16)")],
                default="landscape",
                help_text="Choose video format: landscape (16:9) or reel (9:16)",
                max_length=20,
            ),
        ),
    ]
