# Generated by Django 4.2.15 on 2025-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narration_app", "0008_project_video_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="narration_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="narration_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scene",
            name="audio_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="audio_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scene",
            name="image_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="image_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
