# Generated by Django 4.2.15 on 2025-02-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "narration_app",
            "0009_project_narration_status_project_narration_task_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="narration_task_id",
        ),
        migrations.RemoveField(
            model_name="scene",
            name="audio_task_id",
        ),
        migrations.RemoveField(
            model_name="scene",
            name="image_task_id",
        ),
    ]
